"""inital

Revision ID: 9bbc070521de
Revises: 
Create Date: 2018-12-13 11:02:50.388841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbc070521de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_base_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_url', sa.String(length=250), nullable=False),
    sa.Column('back_url', sa.String(length=250), nullable=False),
    sa.Column('login_url', sa.String(length=250), nullable=False),
    sa.Column('spider_type', sa.Enum('01', '2', '3', '4', '5'), nullable=True),
    sa.Column('parse_method', sa.Enum('jsonxml', 'dir'), nullable=True),
    sa.Column('rule', sa.String(length=100), nullable=False),
    sa.Column('login_header', sa.String(length=512), nullable=True),
    sa.Column('form_data', sa.String(length=512), nullable=True),
    sa.Column('post_url', sa.String(length=250), nullable=True),
    sa.Column('post_header', sa.String(length=512), nullable=True),
    sa.Column('img_url', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_url')
    )
    op.create_table('t_basic_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_url', sa.String(length=250), nullable=False),
    sa.Column('spider_time', sa.String(length=32), nullable=False),
    sa.Column('date_time', sa.String(length=32), nullable=False),
    sa.Column('register', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('msg', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_url')
    )
    op.create_table('t_info_user',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nick_name', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nick_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_info_user')
    op.drop_table('t_basic_data')
    op.drop_table('t_base_info')
    # ### end Alembic commands ###
